proxies:
- name: 1.89|Relay  269Mb
  server: fr-am1-1.eqsunshine.com
  type: ssr
  country: FR
  port: 8181
  password: gVWc0WaJn
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: 1.66|RelayAUAU54  270Mb
  server: sy-am2.eqsunshine.com
  type: ssr
  country: AU
  port: 443
  password: Jz8r4gLNP
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: 1.59| AU01 TGpeekfun
  server: 3.25.172.185
  port: 443
  type: ssr
  country: ' AU'
  password: Jz8r4gLNP
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: 1.58| US153 TGpeekfun
  server: 13.37.227.247
  port: 8181
  type: ssr
  country: ' US'
  password: gVWc0WaJn
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: 1.56|
  server: in-am2.eqnode.net
  type: ssr
  country: IN
  port: 8080
  password: fD0KP8PWA
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
